// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Ad is the golang structure of table sys_ad for DAO operations like Where/Data.
type Ad struct {
	g.Meta `orm:"table:sys_ad, do:true"`
}
