// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// AdSort is the golang structure of table sys_ad_sort for DAO operations like Where/Data.
type AdSort struct {
	g.Meta `orm:"table:sys_ad_sort, do:true"`
}
