// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// City is the golang structure of table sys_city for DAO operations like Where/Data.
type City struct {
	g.Meta `orm:"table:sys_city, do:true"`
}
