// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigData is the golang structure of table sys_config_data for DAO operations like Where/Data.
type ConfigData struct {
	g.Meta `orm:"table:sys_config_data, do:true"`
}
