// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Config is the golang structure of table sys_config for DAO operations like Where/Data.
type Config struct {
	g.Meta `orm:"table:sys_config, do:true"`
}
