// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Dept is the golang structure of table sys_dept for DAO operations like Where/Data.
type Dept struct {
	g.Meta `orm:"table:sys_dept, do:true"`
}
