// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Dict is the golang structure of table sys_dict for DAO operations like Where/Data.
type Dict struct {
	g.Meta `orm:"table:sys_dict, do:true"`
}
