// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DictData is the golang structure of table sys_dict_data for DAO operations like Where/Data.
type DictData struct {
	g.Meta `orm:"table:sys_dict_data, do:true"`
}
