// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Example is the golang structure of table sys_example for DAO operations like Where/Data.
type Example struct {
	g.Meta `orm:"table:sys_example, do:true"`
}
