// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ItemCate is the golang structure of table sys_item_cate for DAO operations like Where/Data.
type ItemCate struct {
	g.Meta `orm:"table:sys_item_cate, do:true"`
}
