// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Item is the golang structure of table sys_item for DAO operations like Where/Data.
type Item struct {
	g.Meta `orm:"table:sys_item, do:true"`
}
