// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Level is the golang structure of table sys_level for DAO operations like Where/Data.
type Level struct {
	g.Meta `orm:"table:sys_level, do:true"`
}
