// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Link is the golang structure of table sys_link for DAO operations like Where/Data.
type Link struct {
	g.Meta `orm:"table:sys_link, do:true"`
}
