// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MemberLevel is the golang structure of table ums_member_level for DAO operations like Where/Data.
type MemberLevel struct {
	g.Meta `orm:"table:ums_member_level, do:true"`
}
