// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Member is the golang structure of table ums_member for DAO operations like Where/Data.
type Member struct {
	g.Meta `orm:"table:ums_member, do:true"`
}
