// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Notice is the golang structure of table sys_notice for DAO operations like Where/Data.
type Notice struct {
	g.Meta `orm:"table:sys_notice, do:true"`
}
