// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Position is the golang structure of table sys_position for DAO operations like Where/Data.
type Position struct {
	g.Meta `orm:"table:sys_position, do:true"`
}
