// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table sys_user for DAO operations like Where/Data.
type User struct {
	g.Meta `orm:"table:sys_user, do:true"`
}
