// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalAdDao is internal type for wrapping internal DAO implements.
type internalAdDao = *internal.AdDao

// AdDao is the data access object for table sys_ad.
// You can define custom methods on it to extend its functionality as you wish.
type AdDao struct {
	internalAdDao
}

var (
	// Ad is globally public accessible object for table sys_ad operations.
	Ad = AdDao{
		internal.NewAdDao(),
	}
)

// Fill with you ideas below.
