// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalAdSortDao is internal type for wrapping internal DAO implements.
type internalAdSortDao = *internal.AdSortDao

// AdSortDao is the data access object for table sys_ad_sort.
// You can define custom methods on it to extend its functionality as you wish.
type AdSortDao struct {
	internalAdSortDao
}

var (
	// AdSort is globally public accessible object for table sys_ad_sort operations.
	AdSort = AdSortDao{
		internal.NewAdSortDao(),
	}
)

// Fill with you ideas below.
