// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalCityDao is internal type for wrapping internal DAO implements.
type internalCityDao = *internal.CityDao

// CityDao is the data access object for table sys_city.
// You can define custom methods on it to extend its functionality as you wish.
type CityDao struct {
	internalCityDao
}

var (
	// City is globally public accessible object for table sys_city operations.
	City = CityDao{
		internal.NewCityDao(),
	}
)

// Fill with you ideas below.
