// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalConfigDataDao is internal type for wrapping internal DAO implements.
type internalConfigDataDao = *internal.ConfigDataDao

// ConfigDataDao is the data access object for table sys_config_data.
// You can define custom methods on it to extend its functionality as you wish.
type ConfigDataDao struct {
	internalConfigDataDao
}

var (
	// ConfigData is globally public accessible object for table sys_config_data operations.
	ConfigData = ConfigDataDao{
		internal.NewConfigDataDao(),
	}
)

// Fill with you ideas below.
