// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalConfigDao is internal type for wrapping internal DAO implements.
type internalConfigDao = *internal.ConfigDao

// ConfigDao is the data access object for table sys_config.
// You can define custom methods on it to extend its functionality as you wish.
type ConfigDao struct {
	internalConfigDao
}

var (
	// Config is globally public accessible object for table sys_config operations.
	Config = ConfigDao{
		internal.NewConfigDao(),
	}
)

// Fill with you ideas below.
