// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalDeptDao is internal type for wrapping internal DAO implements.
type internalDeptDao = *internal.DeptDao

// DeptDao is the data access object for table sys_dept.
// You can define custom methods on it to extend its functionality as you wish.
type DeptDao struct {
	internalDeptDao
}

var (
	// Dept is globally public accessible object for table sys_dept operations.
	Dept = DeptDao{
		internal.NewDeptDao(),
	}
)

// Fill with you ideas below.
