// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalExampleDao is internal type for wrapping internal DAO implements.
type internalExampleDao = *internal.ExampleDao

// ExampleDao is the data access object for table sys_example.
// You can define custom methods on it to extend its functionality as you wish.
type ExampleDao struct {
	internalExampleDao
}

var (
	// Example is globally public accessible object for table sys_example operations.
	Example = ExampleDao{
		internal.NewExampleDao(),
	}
)

// Fill with you ideas below.
