// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalItemCateDao is internal type for wrapping internal DAO implements.
type internalItemCateDao = *internal.ItemCateDao

// ItemCateDao is the data access object for table sys_item_cate.
// You can define custom methods on it to extend its functionality as you wish.
type ItemCateDao struct {
	internalItemCateDao
}

var (
	// ItemCate is globally public accessible object for table sys_item_cate operations.
	ItemCate = ItemCateDao{
		internal.NewItemCateDao(),
	}
)

// Fill with you ideas below.
