// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalLinkDao is internal type for wrapping internal DAO implements.
type internalLinkDao = *internal.LinkDao

// LinkDao is the data access object for table sys_link.
// You can define custom methods on it to extend its functionality as you wish.
type LinkDao struct {
	internalLinkDao
}

var (
	// Link is globally public accessible object for table sys_link operations.
	Link = LinkDao{
		internal.NewLinkDao(),
	}
)

// Fill with you ideas below.
