// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalMemberDao is internal type for wrapping internal DAO implements.
type internalMemberDao = *internal.MemberDao

// MemberDao is the data access object for table ums_member.
// You can define custom methods on it to extend its functionality as you wish.
type MemberDao struct {
	internalMemberDao
}

var (
	// Member is globally public accessible object for table ums_member operations.
	Member = MemberDao{
		internal.NewMemberDao(),
	}
)

// Fill with you ideas below.
