// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalMenuDao is internal type for wrapping internal DAO implements.
type internalMenuDao = *internal.MenuDao

// MenuDao is the data access object for table sys_menu.
// You can define custom methods on it to extend its functionality as you wish.
type MenuDao struct {
	internalMenuDao
}

var (
	// Menu is globally public accessible object for table sys_menu operations.
	Menu = MenuDao{
		internal.NewMenuDao(),
	}
)

// Fill with you ideas below.
