// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalNoticeDao is internal type for wrapping internal DAO implements.
type internalNoticeDao = *internal.NoticeDao

// NoticeDao is the data access object for table sys_notice.
// You can define custom methods on it to extend its functionality as you wish.
type NoticeDao struct {
	internalNoticeDao
}

var (
	// Notice is globally public accessible object for table sys_notice operations.
	Notice = NoticeDao{
		internal.NewNoticeDao(),
	}
)

// Fill with you ideas below.
