// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalPositionDao is internal type for wrapping internal DAO implements.
type internalPositionDao = *internal.PositionDao

// PositionDao is the data access object for table sys_position.
// You can define custom methods on it to extend its functionality as you wish.
type PositionDao struct {
	internalPositionDao
}

var (
	// Position is globally public accessible object for table sys_position operations.
	Position = PositionDao{
		internal.NewPositionDao(),
	}
)

// Fill with you ideas below.
