// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mytrix-technology/admintrix/internal/dao/internal"
)

// internalUserRoleDao is internal type for wrapping internal DAO implements.
type internalUserRoleDao = *internal.UserRoleDao

// UserRoleDao is the data access object for table sys_user_role.
// You can define custom methods on it to extend its functionality as you wish.
type UserRoleDao struct {
	internalUserRoleDao
}

var (
	// UserRole is globally public accessible object for table sys_user_role operations.
	UserRole = UserRoleDao{
		internal.NewUserRoleDao(),
	}
)

// Fill with you ideas below.
