// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Ad is the golang structure for table _ad.
type Ad struct {
}
