// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdSort is the golang structure for table _ad_sort.
type AdSort struct {
}
