// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigData is the golang structure for table _config_data.
type ConfigData struct {
}
