// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Dept is the golang structure for table _dept.
type Dept struct {
}
