// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Dict is the golang structure for table _dict.
type Dict struct {
}
