// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// DictData is the golang structure for table _dict_data.
type DictData struct {
}
