// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Example is the golang structure for table _example.
type Example struct {
}
