// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Item is the golang structure for table _item.
type Item struct {
}
