// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ItemCate is the golang structure for table _item_cate.
type ItemCate struct {
}
