// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Level is the golang structure for table _level.
type Level struct {
}
