// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Link is the golang structure for table _link.
type Link struct {
}
