// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MemberLevel is the golang structure for table _member_level.
type MemberLevel struct {
}
