// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Menu is the golang structure for table _menu.
type Menu struct {
}
