// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Notice is the golang structure for table _notice.
type Notice struct {
}
