// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Position is the golang structure for table _position.
type Position struct {
}
