// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// RoleMenu is the golang structure for table _role_menu.
type RoleMenu struct {
}
