// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserRole is the golang structure for table _user_role.
type UserRole struct {
}
